export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  PLAN_DATE_CONFLICT: "PLAN_DATE_CONFLICT",
  VENDOR_DISABLED: "VENDOR_DISABLED",
  VENDOR_SCOPE_MISMATCH: "VENDOR_SCOPE_MISMATCH",
  PLAN_NOT_ASSIGNED: "PLAN_NOT_ASSIGNED"
} as const;
